### ISSUE TITLE
Example from README doesn't work on proj 9.2.0, proj4rb 3.0.0

### ISSUE THREAD

**Issue by seydar** [cfis/proj4rb#22]
I installed the gem locally from HEAD, and I am unable to get the right answer for the example in the README.

```
irb(main):001:0> require 'proj'
=> true
irb(main):002:0> transform = Proj::Transformation.new('epsg:31467', 'epsg:4326')
=> #<Proj::Transformation:0x000000014901f898 @pointer=#<FFI::Pointer address=0x000000013f8bf6d0>, @context=nil>
irb(main):003:0> from = Proj::Coordinate.new(x: 5428192.0, y: 3458305.0, z: -5.1790915237)
=> #<Proj::Coordinate:0x0000000148016b18 @coord=#<Proj::Api::PJ_COORD:0x0000000148016ac8>>
irb(main):004:0> to = transform.forward(from)
=> #<Proj::Coordinate:0x000000014eb960c8 @coord=#<Proj::Api::PJ_COORD:0x000000014eb96168>>
irb(main):005:0> assert_in_delta(48.98963932450735, to.x, 0.01)
Traceback (most recent call last):
        4: from /Users/ari/.asdf/installs/ruby/3.0.0/bin/irb:23:in `<main>'
        3: from /Users/ari/.asdf/installs/ruby/3.0.0/bin/irb:23:in `load'
        2: from /Users/ari/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
        1: from (irb):5:in `<main>'
NoMethodError (undefined method `assert_in_delta' for main:Object)
irb(main):006:0> assert_in_delta(8.429263044355544, to.y, 0.01)
Traceback (most recent call last):
        5: from /Users/ari/.asdf/installs/ruby/3.0.0/bin/irb:23:in `<main>'
        4: from /Users/ari/.asdf/installs/ruby/3.0.0/bin/irb:23:in `load'
        3: from /Users/ari/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
        2: from (irb):5:in `<main>'
        1: from (irb):6:in `rescue in <main>'
NoMethodError (undefined method `assert_in_delta' for main:Object)
irb(main):007:0> assert_in_delta(-5.1790915237, to.z, 0.01)
Traceback (most recent call last):
        5: from /Users/ari/.asdf/installs/ruby/3.0.0/bin/irb:23:in `<main>'
        4: from /Users/ari/.asdf/installs/ruby/3.0.0/bin/irb:23:in `load'
        3: from /Users/ari/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
        2: from (irb):6:in `<main>'
        1: from (irb):7:in `rescue in <main>'
NoMethodError (undefined method `assert_in_delta' for main:Object)
irb(main):008:0> assert_in_delta(0, to.t, 0.01)
Traceback (most recent call last):
        5: from /Users/ari/.asdf/installs/ruby/3.0.0/bin/irb:23:in `<main>'
        4: from /Users/ari/.asdf/installs/ruby/3.0.0/bin/irb:23:in `load'
        3: from /Users/ari/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
        2: from (irb):7:in `<main>'
        1: from (irb):8:in `rescue in <main>'
NoMethodError (undefined method `assert_in_delta' for main:Object)
irb(main):009:1* [to.x, to.y]
=> [3.026879393e-314, 1.2295657139155186e-27]
```

I believe it should be [48.98963932450735, 8.429263044355544].

**Comment by cfis** [comment]
So assert_id_delta assume you are running it as part of a unit test (that method comes from minitest).

There is this exact test in the test suite - see https://github.com/cfis/proj4rb/blob/master/test/transformation_test.rb#L24. it passes the test runs and I just tried it locally successfully.

So not sure. If you run that test locally, does it pass?

**Comment by seydar** [comment]
`echo "3458305 5428192 -5.1790915237" | cs2cs -f '%.10f' +init=epsg:31467 +to +init=epsg:4326 -` works as expected and produces the correct output `8.4292630550	48.9896327645 -5.1790915237`

**Comment by cfis** [comment]
Weird. Really don't know. I guess most of the tests fail then? What OS are you on (not that it should make a difference)?

The message "Ballpark geographic offset from WGS 84 to unknown + unknown"  seems suspicious. Wonder if somehow  different proj.db is being loaded?

**Comment by cfis** [comment]
Ok, I think I figured it out.  EPSG needs to be capitalized when sent to proj_create (what happens under the hood).

Try:

Proj::Transformation.new('EPSG:31467', 'EPSG:4326')

**Comment by seydar** [comment]
I updated the code to use capitals for EPSG, but the transformation.rb tests still fail in the exact same way.

**Comment by seydar** [comment]
I'm using an Apple M1, ruby 3.0.0p0, proj 9.2.0, proj4b 3.0.0 (HEAD).

Still getting the same issue:

```
irb(main):001:0' require 'proj'
=> true
irb(main):002:0> xform = Proj::Transformation.new "+proj=lcc +lat_1=33 +lat_2=45 +lat_0=0 +lon_0=-100 +x_0=0 +y_0=0 +ellps=WGS84 +towgs84=0,0,0,-0,-0,-0,0 +units=m +no_defs", "EPSG:4326"
=> #<Proj::Transformation:0x000000013ea5e8c8 @pointer=#<FFI::Pointer address=0x000000012f01ba80>, @context=nil>
irb(main):003:0> coord = Proj::Coordinate.new :x => 30, :y => 50
=> #<Proj::Coordinate:0x000000013ecb7840 @coord=#<Proj::Api::PJ_COORD:0x000000013ecb77f0>>
irb(main):004:0> to = xform.forward coord
=> #<Proj::Coordinate:0x000000013eb84bd0 @coord=#<Proj::Api::PJ_COORD:0x000000013eb84c70>>
irb(main):005:1* [to.x, to.y]
=> [3.041466171e-314, 9.933925501494176e-73]
irb(main):006:0> to = xform.inverse coord
=> #<Proj::Coordinate:0x000000013eade618 @coord=#<Proj::Api::PJ_COORD:0x000000013eade730>>
irb(main):007:0> [to.x, to.y]
=> [3.041466171e-314, 9.933925501494176e-73]
```

And while the transformation you listed can be created, it doesn't seem to work:

```
irb(main):001:0> require 'proj'
=> true
irb(main):002:0> xform = Proj::Transformation.new('EPSG:31467', 'EPSG:4326')
=> #<Proj::Transformation:0x00000001428dfe08 @pointer=#<FFI::Pointer address=0x0000000142658620>, @context=nil>
irb(main):003:0> coord = Proj::Coordinate.new :x => 30, :y => 50
=> #<Proj::Coordinate:0x00000001429280b8 @coord=#<Proj::Api::PJ_COORD:0x0000000142928068>>
irb(main):004:0> to = xform.forward coord
=> #<Proj::Coordinate:0x00000001330bc230 @coord=#<Proj::Api::PJ_COORD:0x00000001330bc2d0>>
irb(main):005:1* [to.x, to.y]
=> [3.0486543283e-314, 7.086091718480266e-168]
irb(main):006:0> to = xform.inverse coord
=> #<Proj::Coordinate:0x000000014292a458 @coord=#<Proj::Api::PJ_COORD:0x000000014292a4a8>>
irb(main):007:0> [to.x, to.y]
=> [3.0486543283e-314, 7.086091718480266e-168]
```

**Comment by seydar** [comment]
Just ran the test suite:

```
[ari@zulu: ~/src/proj4rb/test] for f in *; do; ruby $f >> results.txt; done
[ari@zulu: ~/src/proj4rb/test] rg failures results.txt
9:0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
37:17 runs, 529 assertions, 3 failures, 0 errors, 0 skips
115:18 runs, 40 assertions, 6 failures, 0 errors, 0 skips
124:4 runs, 24 assertions, 0 failures, 0 errors, 0 skips
133:6 runs, 6 assertions, 0 failures, 0 errors, 0 skips
173:32 runs, 559 assertions, 4 failures, 1 errors, 0 skips
238:26 runs, 70 assertions, 9 failures, 0 errors, 0 skips
247:4 runs, 6 assertions, 0 failures, 0 errors, 0 skips
256:3 runs, 8 assertions, 0 failures, 0 errors, 0 skips
265:7 runs, 13 assertions, 0 failures, 0 errors, 0 skips
278:2 runs, 3 assertions, 1 failures, 0 errors, 0 skips
287:5 runs, 9 assertions, 0 failures, 0 errors, 0 skips
304:9 runs, 17 assertions, 2 failures, 0 errors, 0 skips
317:1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
331:15 runs, 24 assertions, 1 failures, 0 errors, 0 skips
340:4 runs, 7 assertions, 0 failures, 0 errors, 0 skips
349:5 runs, 7 assertions, 0 failures, 0 errors, 0 skips
367:20 runs, 23 assertions, 2 failures, 0 errors, 0 skips
376:6 runs, 13 assertions, 0 failures, 0 errors, 0 skips
389:8 runs, 19 assertions, 1 failures, 0 errors, 0 skips
398:0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
407:6 runs, 58 assertions, 0 failures, 0 errors, 0 skips
565:14 runs, 28 assertions, 5 failures, 0 errors, 0 skips
574:7 runs, 43 assertions, 0 failures, 0 errors, 0 skips
```

Attached are the STDERR and STDOUT outputs.
[results.txt](https://github.com/cfis/proj4rb/files/10921248/results.txt)
[stderr.txt](https://github.com/cfis/proj4rb/files/10921249/stderr.txt)

**Comment by cfis** [comment]
Ok. Unfortunately I can't duplicate what you are seeing, so not sure what its causing it. I'd check the proj database path and see if it looks right:

https://github.com/cfis/proj4rb/blob/master/test/database_test.rb#L24

Maybe also the proj search paths:

https://github.com/cfis/proj4rb/blob/master/test/proj_test.rb#L17

Then maybe use projinfo (https://proj.org/apps/projinfo.html) and compare what it says versus the Ruby bindings.

Sorry not much that help I know.

FYI, you can run all tests using `rake test`

**Comment by seydar** [comment]
Womp. Can't find the DB. Any advice for fixing that?

Attached is `rake test`.
[out.txt](https://github.com/cfis/proj4rb/files/10946388/out.txt)

**Comment by cfis** [comment]
Ah - that explains it! So PROJ_LIB is the old ENV, its not PROJ_DATA (but PROJ_LIB still works).  See https://proj.org/usage/environmentvars.html#envvar-PROJ_DATA.

Just make sure PROJ_DATA is set right (you can't set it in side the ruby program has to be before it runs).

Alternatively, in your script, you can use this method on Context:

https://rubydoc.info/github/cfis/proj4rb/Proj%2FContext:search_paths=

Or this one on Database:

https://rubydoc.info/github/cfis/proj4rb/Proj/Database#path=-instance_method

What doesn't quite make sense though is you said the proj executables run without issue. Thus the Ruby bindings should work too.

**Comment by seydar** [comment]
It feels good to get closer! Unfortunately, I still can't get it to work. I'm going to give up for now and just use `cs2cs` to do some bulk data transformation.
